name = "dark"

background     = "#18181b"
foreground     = "#e4e4e7"
currentLineBg  = "#27272a"
lineNumberFg   = "#52525b"
lineNumberBg   = "#18181b"
selectionBg    = "#253b59"
selectionFg    = "#f4f4f5"
cursorColor    = "#60a5fa"
searchHighlightBg = "#eab3084d"

[heading]
h1 = "#fb7185"
h2 = "#fbbf24"
h3 = "#34d399"
h4 = "#38bdf8"
h5 = "#a78bfa"
h6 = "#e879f9"

[code]
inlineFg  = "#f87171"
inlineBg  = "#27272a"
fenceFg   = "#93c5fd"
fenceBg   = "#242734"
langFg    = "#71717a"

[block]
blockquoteFg     = "#a1a1aa"
blockquoteBorder = "#3f3f46"
listBullet       = "#60a5fa"
linkText         = "#22d3ee"
linkUrl          = "#52525b"
image            = "#c084fc"
bold             = "#ffffff"
italic           = "#d4d4d8"
strike           = "#71717a"
tablePipe        = "#52525b"
hr               = "#3f3f46"
marker           = "#fde047"
hardBreak        = "#f43f5e"

[latex]
delimiter  = "#c084fc"
command    = "#fb7185"
brace      = "#fbbf24"
mathBody   = "#fde68a"
envName    = "#34d399"
